Update translations to upstream at 2021-03-05 (Closes #183)
lxc-jp/lxd-ja pull request #184
Opened 2021-03-05 13:07 UTC by hnakamur

* doc/rest-api.yaml は翻訳対象外とさせていただいています (doc/rest-api.md とは別。最後の行見ると Swagger で使うためのファイルのようです)。
* doc/server.md と doc/storage.md は表から API extension の列を削除しているだけです。

Signed-off-by: Hiroaki Nakamura <hnakamur@gmail.com>

2021-03-05 17:04 UTC, tenforward commented
少しずつチェックしています。
訳注で指摘している原文の間違いは本家には報告されてますか?

2021-03-05 23:11 UTC, hnakamur commented
チェックありがとうございます。
原文の間違い報告してなかったので今報告しました。

* [Fix typo in doc/projects.md, replace images with backups by hnakamur · Pull Request #8534 · lxc/lxd](https://github.com/lxc/lxd/pull/8534)
* [Fix a typo in rest-api.md for renaming a network ACL by hnakamur · Pull Request #8535 · lxc/lxd](https://github.com/lxc/lxd/pull/8535)

2021-03-07 12:04 UTC, tenforward requested changes
新規文書もあったりするところ、素早い翻訳ありがとうございました。以下、ご確認ください。

2021-03-07 12:09 UTC, tenforward commented
あと、原文の間違いがあった部分、翻訳でも修正しておいて良いと思います！

2021-03-07 12:18 UTC, hnakamur commented
コメントありがとうございます。修正しました。

2021-03-07 12:23 UTC, merged