Update translations of LXD 4.23 (Closes #214)
lxc-jp/lxd-ja pull request #215
Opened 2022-02-13 12:59 UTC by hnakamur

* [LXD 4.22 で英語ドキュメントが Sphinx に移行した](https://discuss.linuxcontainers.org/t/lxd-4-22-has-been-released/13137#improved-documentation-4) のを受けて今回日本語ドキュメントも移行しました。
    * ローカルでのビルド手順が [doc/README.md](https://github.com/lxc-jp/lxd-ja/blob/update-2022-02-11/doc/README.md)](https://github.com/lxc-jp/lxd-ja/blob/4223878633c8e12cd6a11daf741f1c09cfc2f4d0/doc/README.md) で説明されています。
    * 使用している Markdown + MyST 拡張については [doc/doc-cheat-sheet.md](https://github.com/lxc-jp/lxd-ja/blob/4223878633c8e12cd6a11daf741f1c09cfc2f4d0/doc/doc-cheat-sheet.md) に説明があります。
    * 本家は [.github/workflows/sphinx.yml](https://github.com/lxc/lxd/blob/81512e0826f151004b9ccd492a32b5af75ceaf58/.github/workflows/sphinx.yml) のワークフローで GitHub Actions で Makefile から Sphinx を実行してドキュメントをビルドしています。
    * 日本語訳の方は readthedocs でビルドできるようにするため、いくつか調整を行いました。
        * `.readthedocs.yaml` ファイルを追加。設定項目については [Configuration File V2 — Read the Docs user documentation 7.2.0 documentation](https://docs.readthedocs.io/en/stable/config-file/v2.html) を参照。当初 readthedocs のプロジェクトの設定画面から設定していたのですがこのファイルで設定するほうがお勧めとのメッセージが表示されたので移行しました。このファイルがあると画面からの設定よりこのファイルのほうが優先されるそうです。
        * .sphinx/ 以下の conf.py やディレクトリを doc/ 以下に移動。
            * 本家のディレクトリ構成ではSphinxの設定ファイルは `.sphinx/conf.py` にあってドキュメントは `doc/` 以下にあるのですが、readthedocs だとシンボリックリンクを駆使ししてみても index の1ファイルしか表示されませんでした。
            * [Where do I need to put my docs for RTD to find it?](https://docs.readthedocs.io/en/stable/faq.html#where-do-i-need-to-put-my-docs-for-rtd-to-find-it) を見ると `conf.py` とドキュメントは同じディレクトリに置く必要があるようなので `conf.py` や `.sphinx/` 以下にあったディレクトリを `doc/` 以下に移動し、Makefile も適宜調整しました。
            * ビルド時に取得するファイルを `doc/_static/swagger-ui/` と `doc/_static/download/` 以下にコミットしました。Swagger のJS、CSSファイルとLXDのロゴ画像です。これも readthedocs でビルドする際には予め配置しておく必要がありそうだったので追加しました。
    * なお Read the Docs でも Markdown + MyST 拡張で Sphinx のドキュメントをビルドできます。 [Getting Started with Sphinx — Read the Docs user documentation 7.2.0 documentation](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx)
    * 前回のコミットから 4.22 を Sphinx に移行するまでの差分 https://github.com/lxc-jp/lxd-ja/compare/0ff79eac6aebb30395417721375cacf507eb41f5...c056305cba9e7f76ce91b260d72f6e01900ca82b
        * プロジェクトトップディレクトリの `*.md` ファイルを追加しました。
        * `shared/` ディレクトリを追加しました。 `make doc` でのビルド時にないとエラーになったので。
        * `doc/` 以下は一旦 4.22 の英語のドキュメントで上書きして Sphinx でのビルドがうまくいくようになってから、 4.22 の日本語訳に置き換えて Sphinx で問題ないように調整しました。
        * `doc/rest-api.yaml` だけ間違ってこの時点で 4.23 のファイルを含めてしまいました。このファイルは翻訳対象外ということもありこのままにしています。
* このプルリクエストの本題
    * 日本語訳の 4.22 から 4.23 への変更内容 https://github.com/lxc-jp/lxd-ja/compare/c056305cba9e7f76ce91b260d72f6e01900ca82b...4223878633c8e12cd6a11daf741f1c09cfc2f4d0
    * 原文の 4.22 から 4.23 への変更内容 https://github.com/lxc-jp/lxd-ja/compare/5d7207337ab9220564a649119acc7322284e6ef5...5719afc6184383884e640e00fc5d4786ecb5c3d2

2022-02-17 13:24 UTC, tenforward commented
`SUPPORT.md` というファイルがトップにありますけど、lxd 本家の方にはないですね。`.github/SUPPORT.md` というファイルはありますが、今回の PR で追加されている（?）ものとは中身が違います。

2022-02-17 13:44 UTC, hnakamur commented
あ、本当ですね。すみません。今確認したところ、4.22 ではあったんでした。
https://github.com/lxc/lxd/blob/lxd-4.22/SUPPORT.md
4.22→4.23への差分を確認しやすいようにと思って一旦4.22の訳を作ったんですが4.23で削除されてたんですね。
ということで削除しました。

2022-02-18 14:04 UTC, tenforward requested changes
一通りざっとみてコメントしています。

* 文章の途中で改行がある場合のおかしな翻訳が結構ありました。一応全部見たつもりですが抜けがあるかもしれません。機械翻訳系は改行を無視してくれませんよね…
* チェックは「日本語訳の 4.22 から 4.23 への変更内容 c056305...4223878」の差分を見ながら行ったので、それ以外の部分に抜けがあるかもしれません（一応全ファイルざっとはなめてます）
* Makefileやyamlなどのドキュメントビルド系の設定ファイルなどは見てません
* shared/ 以下 go のソースファイルが混入しています（当たり前ですが、これも見てません）
* コメントとして入れてありますが、CODE_OF_CONDUCT.md は外部文書なので、翻訳に関するコメントはしたのですが無視してください。この文書自体、日本語訳があるのでそれをコピペするか、そもそも include とかしていないのであれば、このファイル自体 lxd-ja からは抜いてしまってもいいと思います（ドキュメント中にリンクがあるのならオリジナルサイトに飛ばす）

2022-02-18 14:44 UTC, hnakamur commented on doc/projects.md
> +## プロジェクトのセキュリティ規制
https://github.com/lxc-jp/lxd-ja/blob/0ff79eac6aebb30395417721375cacf507eb41f5/doc/projects.md
でこの上に「プロジェクトの制限」(limits)とあって「プロジェクトに対する制限 」(restriction) と limit と restriction を両方「制限」と訳してたので区別つけたほうが良いかなと思って変更してみたんですが、「制限」のほうが良さそうでしょうか？

2022-02-18 15:01 UTC, hnakamur commented on doc/authentication.md
> +トークンはクッキーとして保存され、クライアントがLxDにリクエストするたびに提示されます。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:01 UTC, hnakamur commented on doc/authentication.md
> +認証が成功した場合、クライアントはLxDサーバに接続し、認証サーバから受け取ったトークンを提示します。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:02 UTC, hnakamur commented on doc/authentication.md
> +このモードでは、LXDデーモンへの接続はすべて、あらかじめ用意されたCA証明書を使って行われます。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:02 UTC, hnakamur commented on doc/authentication.md
> +我々はクライアントとサーバーの両方を管理しているので、壊れたプロトコルやサーバーの下位互換をサポートする理由はありません。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:03 UTC, hnakamur commented on doc/security.md
> +プロファイルで設定されたデフォルトのブリッジドNICの設定は、インスタンスごとに以下の方法で上書きすることができます。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:06 UTC, hnakamur commented on doc/image-handling.md
> +requirements.cgroup     | string | -          | "v1" "に設定されている場合、イメージはホストがCGroupV1を実行することを必要とすることを示します。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

なるほど、cgroup を実行するというと違和感ありますか。まあでも原文も "run CGroupV1" となっているのでご提案頂いた訳を使わせていただきますね。

2022-02-18 15:07 UTC, hnakamur commented on doc/image-handling.md
> +インスタンスの互換性を判断するために使用されます。これらの互換性がない場合には
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:08 UTC, hnakamur commented on doc/authentication.md
> +信頼されている他のクライアントや、ローカルのサーバー管理者が、サーバー上のクライア ントの信頼エントリを削除すると、そのクライアントに対するサーバーの信頼関係は失効します。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:08 UTC, hnakamur commented on doc/authentication.md
> +### サーバーの信頼関係が破棄されました
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:09 UTC, hnakamur commented on doc/authentication.md
> +   - クライアントの証明書がサーバーのトラストストアにある場合は、接続が許可されます。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。
他の「クライアントの証明書」も「クライアント証明書」に揃えました。

2022-02-18 15:09 UTC, hnakamur commented on doc/api-extensions.md
> +OVNネットワークに関連する追加の状態情報を含みます。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 15:10 UTC, hnakamur commented on doc/authentication.md
> +壊れたプロトコルや暗号の後方互換性をサポートする理由はありません。
ありがとうございます。 https://github.com/lxc-jp/lxd-ja/pull/215/commits/a05175f4beabbbed92f82cbad9a80b76eca1a67f で修正しました(差分: https://github.com/lxc-jp/lxd-ja/compare/67c8d1d7af4d960ee76c86d9b44e2b5d2629bb6b...a05175f4beabbbed92f82cbad9a80b76eca1a67f )。

2022-02-18 16:30 UTC, tenforward commented on doc/projects.md
> +## プロジェクトのセキュリティ規制
あー、なるほど。了解です。そのままで行きましょう。

2022-02-18 16:33 UTC, tenforward approved these changes

2022-02-18 16:33 UTC, merged