Update translation of LXD 5.1 (Closes #221)
lxc-jp/lxd-ja pull request #222
Opened 2022-05-01 02:29 UTC by hnakamur

* 原文の変更
    * 原文のdocの5.0.0から5.1への差分: https://github.com/lxc-jp/lxd-ja/commit/5f69cd58b79e10fc43ebb3dd7610d2a2261c7893
    * 私が送ったtypo修正プルリクエスト: [doc: Fix typos by hnakamur · Pull Request #10353 · lxc/lxd](https://github.com/lxc/lxd/pull/10353)
    * ビルド済みドキュメント: https://linuxcontainers.org/lxd/docs/master/
* 日本語訳の変更
    * 日本語訳のdocの5.0.0から5.1への差分: https://github.com/lxc-jp/lxd-ja/commit/590174c3e9d4bcec302737bfa2972868f56d6cde
    * shared以下を原文の5.1の内容で更新: https://github.com/lxc-jp/lxd-ja/commit/3cefed7e9d39ca14fc94444b60ed349fd68ddccb
    * ローカルでmake docでドキュメントをビルドして気づいたリンク切れと項目タイトル抜け修正 https://github.com/lxc-jp/lxd-ja/commit/ebad168cc4b424ab211960b84aa9565ca052fd23
    * ビルド済みドキュメント: https://lxd-ja-staging.readthedocs.io/ja/latest/

2022-05-01 02:30 UTC, hnakamur commented
ブリッジネットワークと物理ネットワークは `bridge` と `physical` を入れるかどうかが悩ましいです。文中では「ブリッジネットワーク」と「物理ネットワーク」で良いと思うのですが https://lxd-ja-staging.readthedocs.io/ja/latest/howto/network_create/ のネットワークタイプの値としては `bridge` や `physical` なので。
今は一部で (`physical`) とつけているのですが、いかがでしょうか？

2022-05-02 09:37 UTC, tenforward requested changes

2022-05-02 10:51 UTC, hnakamur commented on doc/explanation/networks.md
> +最も簡単な方法は LXD の初期化時にネットワークブリッジを作って全てのインスタンスでこのブリッジを使うことですが、 LXD はネットワークの多くの異なる高度な設定をサポートします。
ありがとうございます。ご提案の訳に更新しました。

2022-05-02 10:51 UTC, hnakamur commented on doc/explanation/networks.md
> +  LXD の文脈では、 `bridge` ネットワークタイプはインスタンスに接続し単一の L2 ネットワークセグメントにするような L2 ブリッジを作成します。
ありがとうございます。ご提案の訳に更新しました。

2022-05-02 10:51 UTC, hnakamur commented on doc/explanation/networks.md
> +完全に制御されたネットワークを選ぶ場合は、ネットワークデバイスを使用するのに比べてより多くの機能を提供します。
ありがとうございます。ご提案の訳に更新しました。

2022-05-02 10:51 UTC, hnakamur commented on doc/reference/network_physical.md
> +parent                          | string    | -                | -                                         | sriov NIC を作成する親のインターフェース
ありがとうございます。ご提案の訳に更新しました。

2022-05-02 10:52 UTC, hnakamur commented on doc/reference/network_physical.md
> +dns.nameservers                 | string    | 標準モード       | -                                         | 物理ネットワークの DNS サーバ IP のリスト
ありがとうございます。修正しました。

2022-05-02 10:52 UTC, hnakamur commented on doc/howto/network_bgp.md
> +すると LXD は BGP ピアとして振る舞い関連するルートとネクストホップを外部のルータ、例えばあなたのネットワークルータに広告します。
ありがとうございます。修正しました。

2022-05-02 10:53 UTC, hnakamur commented on doc/explanation/networks.md
> +インスタンスへの直接のネットワークアクセスを許可するには、最低 1 つのネットワークデバイス、 {abbr}`NIC (Network Interface Controller)` とも呼ばれる、を割り当てる必要があります。
ありがとうございます。ご提案の訳に更新しました。

`{abbr}` はカーソル当てて「？」になったあと1秒ぐらい待つとカッコ内の略語の説明がツールチップで表示されるようになっています。

2022-05-02 16:26 UTC, tenforward commented
> ブリッジネットワークと物理ネットワークは bridge と physical を入れるかどうかが悩ましいです。

日本語訳と同時に設定値（`physical`とか`bridge`）を補足した方がわかりやすい部分は「ブリッジネットワーク（`bridge`）」のように併記、特に併記しなくてもいい部分は日本語訳のみという感じでいいのではないでしょうか。（答えになってます？）

2022-05-02 16:26 UTC, merged