Update translation of LXD 5.3 (Closes #225)
lxc-jp/lxd-ja pull request #226
Opened 2022-06-25 13:08 UTC by hnakamur

* 原文
    * 原文のdocの5.2から5.3への差分: https://github.com/lxc-jp/lxd-ja/commit/4aadaa888d7e6b9ad22659a699c7a9c14847d12e
    * ビルド済みドキュメント(5.3からさらに更新あり): https://linuxcontainers.org/lxd/docs/master/
* 日本語訳
    * 日本語訳のdocの5.2から5.3への差分: https://github.com/lxc-jp/lxd-ja/commit/2d1106db8f1e1d0fcbdc957461635c9c3c2bffca ( instances.md などでは表の列幅を変えているため  https://github.com/lxc-jp/lxd-ja/commit/2d1106db8f1e1d0fcbdc957461635c9c3c2bffca?w=1 で空白無視の差分を見るほうが変更点がわかりやすいと思います。)
    * ビルド済みドキュメント: https://lxd-ja-staging.readthedocs.io/ja/latest/
    * sharedフォルダの5.2から5.3の差分取り込み: https://github.com/lxc-jp/lxd-ja/commit/ef826207cc169452ebf02e3401e91021df9759f6

2022-07-02 16:29 UTC, tenforward requested changes

2022-07-02 16:29 UTC, tenforward commented on doc/howto/storage_create_pool.md
> +```
この文書ですが、「作成。」と「作成する。」が混在しているのでどちらかに統一しませんか?

2022-07-03 00:00 UTC, hnakamur commented
膨大な変更量のレビューありがとうございます！
雑なタイポが残っていてすみませんでした。
https://github.com/lxc-jp/lxd-ja/pull/226/commits/0bf4d0e80572a63fe42bf7c6eba9627a5ec9e912 でご指摘いただいた変更を反映しました。
https://lxd-ja-staging.readthedocs.io/ja/latest/ も更新しました。

2022-07-03 12:57 UTC, tenforward approved these changes

2022-07-03 12:57 UTC, merged