Update translation of LXD 5.5 (Closes #229)
lxc-jp/lxd-ja pull request #230
Opened 2022-08-21 09:15 UTC by hnakamur

* 原文
    * 原文のdocの5.4から5.5への差分: https://github.com/lxc-jp/lxd-ja/commit/061ece5e23d2e2b04f82f0d0bcf4c23fe4286756
    * ドキュメント修正のマージ済みプルリクエスト 
        * [Doc: Fix typo in howto/storage_backup by hnakamur · Pull Request #10821 · lxc/lxd](https://github.com/lxc/lxd/pull/10821)
        * [doc: backquote mac in doc/api-extensions.md by hnakamur · Pull Request #10822 · lxc/lxd](https://github.com/lxc/lxd/pull/10822)
        * [doc: backqoute cloud-init in doc/cloud-init.md by hnakamur · Pull Request #10823 · lxc/lxd](https://github.com/lxc/lxd/pull/10823)
        * [doc: backquote instance types in events.md by hnakamur · Pull Request #10824 · lxc/lxd](https://github.com/lxc/lxd/pull/10824)
        * [doc: backquote true and NO_PROXY in doc/server.md by hnakamur · Pull Request #10826 · lxc/lxd](https://github.com/lxc/lxd/pull/10826)
    * まだマージされていないプルリクエスト
        * [Doc: Uses more backquotes in documents by hnakamur · Pull Request #10828 · lxc/lxd](https://github.com/lxc/lxd/pull/10828)
* 日本語訳
    * sharedフォルダの5.4から5.5の差分取り込み: https://github.com/lxc-jp/lxd-ja/commit/f60b9ec929b0ac4beda50125f24c548c285cf4ab    * 日本語訳のdocの5.4から5.5への差分: https://github.com/lxc-jp/lxd-ja/commit/a28916a25983a44c3ef644b5fc0e69d097cba605
    * 「ドライバー」を「ドライバ」に置換: https://github.com/lxc-jp/lxd-ja/commit/76e4d76fd37694fac4cd2f1bb24e8edb3126239a
    * ビルド済みドキュメント: https://lxd-ja-staging.readthedocs.io/ja/latest/

なお、原文の変更には `{spellexception}` というのが何箇所か追加されていますが、ローカルの環境でSphinxのビルドを実行した際に警告が出たので日本語訳には  `{spellexception}` は含めていません。

2022-08-22 08:06 UTC, hnakamur commented
btrfs, lvm, zfsのサイズプロパティのデフォルト値を 「`auto`」 から「自動」に変更しました https://github.com/lxc-jp/lxd-ja/pull/230/commits/6f47c775802482fc27fb1a9a7ec416a2fb2267aa (https://github.com/lxc/lxd/pull/10828#discussion_r951108448 の指摘を受けて)

2022-08-22 09:06 UTC, hnakamur commented
[Doc: Uses more backquotes in documents by hnakamur · Pull Request #10828 · lxc/lxd](https://github.com/lxc/lxd/pull/10828) は先程マージされました。

2022-09-08 16:12 UTC, tenforward requested changes

2022-09-08 16:12 UTC, tenforward commented on doc/security.md
> +LXDはUnixソケットを介してローカルにアクセスできるデーモンで、設定されていれば{abbr}`TLS(Transport Layer Security)`ソケットを介してリモートにアクセスすることもできます。
（これは対応不要な独り言ですw）UNIX は "UNIX" でいいような気がしますよねえ。"Unix" の方が違和感あるけど商標だからわざと機能面を表すために "Unix" にしてるんですかね?w

2022-09-09 09:10 UTC, hnakamur commented on doc/security.md
> +LXDはUnixソケットを介してローカルにアクセスできるデーモンで、設定されていれば{abbr}`TLS(Transport Layer Security)`ソケットを介してリモートにアクセスすることもできます。
原文での変更は https://github.com/lxc/lxd/commit/1bf0cf4fec90b3be19bfa76e3cd84b65a55ad0ba のコミットですね。
今回から原文には  `{spellexception}` というのが入ったり、このコミットのメッセージにも `fix spelling` とあるので、おそらくスペルチェッカーを導入されて、それでエラーになったので変更されたのではないかと推測しています。

2022-09-09 09:12 UTC, hnakamur commented on doc/howto/import_machines_to_instances.md
> +   1. コンテナの場合、任意で追加でファイルシステムのマウントを指定できます。
ありがとうございます。後者にしました。

2022-09-09 09:12 UTC, hnakamur commented on doc/explanation/networks.md
> +  LXD の文脈では、 `macvlan` ネットワークタイプは親の Macvlan インタフェースへインスタンスを接続する際に使用するプリセット設定を提供します。
ありがとうございます。間違えていました。
原文の変更が、スペルチェックにひっかかりそうなものはバッククォートで囲むか、固有名詞で先頭を大文字にするという意図を感じたのでそのノリで淡々と修正していて、ここは違うケースだったのを見落としていました。

2022-09-09 09:13 UTC, hnakamur commented on doc/howto/import_machines_to_instances.md
> +このツールはコンテナと仮想マシンの療法を作成できます。
これ以外にも、何箇所も誤変換が残っていて。ローカルでビルドして確認して、stagingでも確認したはずが、自分のミスはなかなか気づかないものですね。
修正しました。

2022-09-09 09:13 UTC, hnakamur commented on doc/howto/import_machines_to_instances.md
> +  また使用中の物理マシンから仮想マシンを作成することもできません。これはマイグレーションツールがコピーしようとするディスクを使用中になるからです。
そうですね、後者にしました。

2022-09-09 09:13 UTC, hnakamur commented on doc/howto/import_machines_to_instances.md
> +  変わりに、起動可能なディスク、起動可能なパーティション、または現在使用中でないディスクを用意してください。
修正しました。

2022-09-09 09:14 UTC, hnakamur commented on doc/howto/import_machines_to_instances.md
> +      次に生成されたトークンをツールを認証するのに使用してください。
入れました。

2022-09-09 09:16 UTC, hnakamur commented on doc/howto/move_instances.md
> +: 移動元のサーバに移動先のサーバに接続させインスタンスをプッシュするように指示します。
「、」を入れて「へ」に変えました。

2022-09-09 09:16 UTC, hnakamur commented on doc/howto/move_instances.md
> +コンテアのライブマイグレーションを使用したい場合、移動元と移動先の療法で CRIU を有効にする必要があります。
修正しました。

2022-09-09 09:18 UTC, hnakamur commented on doc/howto/storage_resize_bucket.md
> +ストレージバケットクォータを設定するには、サイズ設定を設定します。
確かに。configurationを設定として、動詞のsetも設定してとしてしまっていました。
修正しました。

2022-09-09 09:18 UTC, hnakamur commented on doc/reference/storage_cephobject.md
> +Ceph クラスタをどのようにセットアップするかの情報については [Manual Deployment](https://docs.ceph.com/en/latest/install/manual-deployment/) を `radosgw` 環境をどのようにセットアップするかについては [`radosgw`](https://docs.ceph.com/en/latest/radosgw
「、そして」を入れました。

2022-09-09 09:32 UTC, hnakamur commented
https://github.com/lxc-jp/lxd-ja/pull/230/commits/4bd2c5bdd83ddf515d80c90875438e9ebbad1814 で修正して https://lxd-ja-staging.readthedocs.io/ja/latest/ も更新しました。

2022-09-09 09:53 UTC, merged