Update translation of LXD 5.14 (Closes #247)
lxc-jp/lxd-ja pull request #248
Opened 2023-05-26 14:11 UTC by hnakamur

* 原文
    * 原文のdocの5.13から5.14への差分 https://github.com/lxc-jp/lxd-ja/commit/8259695e5221a74ce6d8af7426d97a275b62efa2
    * 私が送ってマージ済みのプルリクエスト: [doc: Fix descrption for lxd_memory_Inactive_anon_bytes metric by hnakamur · Pull Request #11733 · lxc/lxd](https://github.com/lxc/lxd/pull/11733) (このプルリクエストもマージ済みの原文に対応させています)
    * 私が立てたイシュー: [doc: "`eth1` in the example from the previous question", but no `eth1` there · Issue #11730 · lxc/lxd](https://github.com/lxc/lxd/issues/11730)
* 日本語訳
    * sphinx設定の5.13から5.14への取り込み https://github.com/lxc-jp/lxd-ja/commit/a4f12d372942b0d93ace185c76544e917b44711a
    * sharedフォルダの5.13から5.14への取り込み https://github.com/lxc-jp/lxd-ja/commit/f4cb979aeee6b57ff5741a26d1bc645e1633bb40
    * 日本語訳の5.13から5.14への変更 https://github.com/lxc-jp/lxd-ja/commit/77b7f14c738a68a5a6ca4e89befcc54972bc0c75
    * ビルドしたドキュメント https://lxd-ja.readthedocs.io/ja/staging/

2023-06-06 16:33 UTC, tenforward requested changes

2023-06-06 16:33 UTC, tenforward commented on doc/reference/provided_metrics.md
> +  - アクティブLRUリスト上のファイルでバックアップされたメモリの量
"file-backed memory" ですが、要はファイルキャッシュのことだと思います。ちょっとイコールかどうかまでは自信がないのですが、ディスクから読み込んだファイルで、メモリーの解放が必要になったときはディスクに書き戻せるメモリー領域が "file-backed memory" なのだと思います。という意味を含めて「ファイルでバックアップされた」という表現であれば良いと思いますが、それでも括弧書き付きで「ファイルでバックアップされた（file-backed）」みたいに書いたほうが良い気がします。色々書くのがややこしければ、パッと見意味がわからなくなりますが「file-backedなメモリ」でもいいような気がします。（→ [参考](https://enakai00.hatenablog.com/entry/20110906/1315315488)）

2023-06-06 16:33 UTC, tenforward commented on doc/reference/provided_metrics.md
> +  - インアクティブLRUリスト上のファイルでバックアップされたメモリの量
こちらも上記コメントと同じです。ActiveなLRUリストに乗ってるか、InActiveなリストに乗ってるかの違い。

2023-06-06 16:33 UTC, tenforward commented on doc/reference/provided_metrics.md
> +  - ディスクへの書き込み待ちのメモリの量
"written back" なので「書き戻し待ち」でしょうか。

2023-06-06 16:33 UTC, tenforward commented on doc/reference/provided_metrics.md
> +  - swapでバックアップされたキャッシュされたファイルシステムデータの量
"swap-backed"はいざとなればスワップに書き出されるメモリーということで、スワップされているのではないと思います。「バックアップ」を使うなら「スワップにバックアップできる」という感じでしょうか。こちらもわかりづらくなるの覚悟で「swap-backedな〜」でも良いかと思います。それだと意味が分からなくなりそうなので「swap-backed（スワップできる）」という感じ?
[このページ](https://nopipi.hatenablog.com/entry/2015/09/13/181026)の表に「スワップアウトして解放」と「ディスク同期して解放」という言葉がありますね。"swap-backed"=「スワップアウトして解放できるメモリ（swap-backed）」、"file-backed"=「ディスク同期して解放できるメモリ（file-backed）」って表現もありかもしれませんね。

2023-06-06 16:33 UTC, tenforward commented on doc/reference/provided_metrics.md
> +  - 再生不可のメモリの使用量
「再生不可」→「回収不可」ですかね〜。Linuxカーネルによるメモリー回収処理対象にならないメモリーのことかと思います。こちらも[このあたりが参考になりますかね](https://enakai00.hatenablog.com/entry/20110906/1315315488)

2023-06-06 16:33 UTC, tenforward commented on doc/reference/provided_metrics.md
> +  - ディスクへの同期のためみキューに入れられているメモリの量
「ためみ」→「ために」ですね。

2023-06-06 20:05 UTC, hnakamur commented on doc/api-extensions.md
> +これにより、オフラインのクラスターメンバーを自動的に避難させるクラスターヒーリングが追加されます。
そうですね。全てのファイルで「待避」「避難」を「退避」に統一しました。

2023-06-06 20:05 UTC, hnakamur commented on doc/authentication.md
> +LXDクライアントはその後、アクセストークンとリフレッシュトークンを取得し保存し、それらをLXDとのすべてのインタラクションに提供します。
確かにそうですね。provide＝提供にとらわれすぎでした。「それらをLXDとのすべてのやりとりに使用します」にしました。

2023-06-06 20:10 UTC, hnakamur commented on doc/reference/provided_metrics.md
> +  - swapでバックアップされたキャッシュされたファイルシステムデータの量
ありがとうございます。「ディスク同期して解放できる（file-backed）メモリの量」に修正しました。
`lxd_memory_Shmem_bytes` は「スワップアウトして解放できる（swap-backed）キャッシュされたファイルシステムデータの量」に修正しました。
また改めて見てみると「インアクティブ」はわかりにくいと思ったので「非アクティブ」にしました。

2023-06-06 20:11 UTC, hnakamur commented on doc/reference/provided_metrics.md
> +  - アクティブLRUリスト上のファイルでバックアップされたメモリの量
https://github.com/lxc-jp/lxd-ja/pull/248#discussion_r1220265657 にコメントしました。

2023-06-06 20:11 UTC, hnakamur commented on doc/reference/provided_metrics.md
> +  - インアクティブLRUリスト上のファイルでバックアップされたメモリの量
https://github.com/lxc-jp/lxd-ja/pull/248#discussion_r1220265657 にコメントしました。

2023-06-06 21:08 UTC, hnakamur commented
「退避」に統一したついでに、クラスター、メンバ、サーバの表記ゆれをクラスタ、メンバー、サーバーに統一しました。クラスタも長音ありにしようかと思ったのですが、クラスターメンバーと声に出して読むと長い感じを受けたので、クラスタだけ長音なしにしてみました。

また、ほとんどの箇所ではクラスタメンバーと書いているのに1か所だけクラスタ・メンバーだったので中点・を無しにしました。それに伴い、クラスタ・リーダーもクラスタリーダーにしました。中点ありのほうが見やすそうな気もしますがとりあえず。それを言い出すとサーバーオプションとかも中点ありにしたほうが良いかもしれません。

このへんの表記には特にこだわりはないので、変更したほうがよければご指摘ください。
```
rg -l サーバ | xargs -n 1 sed -i 's/サーバ/サーバー/g'
rg -l サーバーー | xargs -n 1 sed -i 's/サーバーー/サーバー/g'
```
みたいな感じで手軽に修正できますので。

上でクラスターオプションだと声に出して読むと長いと言いつつ、サーバーオプションというのに気づいてしまいました。それならクラスタも長音アリでもいいのかも。どうでしょうか？

2023-06-06 21:15 UTC, hnakamur commented
あと[【RHEL】linuxメモリのfreeとmeminfoの関係を図解し利用率の計算方法を説明してみる - のぴぴのメモ](https://nopipi.hatenablog.com/entry/2015/09/13/181026)では「無名ページ」とanonymousを「無名」と訳されていることに気付きました。こちらでは「アノニマス」とカタカナにしていたのですが「無名」にしたほうが良いでしょうか？

2023-06-07 13:26 UTC, tenforward commented on doc/api-extensions.md
> +これにより、オフラインのクラスターメンバーを自動的に避難させるクラスターヒーリングが追加されます。
ここってインスタンス落ちたらCeph使ってる場合はストレージにあるイメージで別ホストから起動する、みたいな話で evacuate 使ってると思うんですけど、なんか微妙に違う気がしなくもないです…w

2023-06-07 13:34 UTC, merged